dictionary = {
    "en": {
        "ロールの色を変更しました": "Changed the color of the role",
        "変更されたロール：" : "Changed role: ",
        "エラー": "Error",
        "このbotに次のロールの色を変更する権限がありません: " : "This bot does not have permission to change the color of the following roles: ",
        "このbotのロールを一番上に設定するなどして、権限の調整を行ってから、再度試してみてください。" : "Please adjust the permissions by setting the role of this bot to the top and try again.",
        "次のロールが存在しません: " : "The following role does not exist: ",
        "色選択をする直前に削除されたものと思われます。" : "It seems that it was deleted just before selecting the color.",
        "ロールの色を変更します" : "Change the color of the role",
        "色を変更するロールの名前" : "Name of the role to change the color",
        "以下から色を選択してください" : "Please select a color from below",
        "ロールの色をRGBで指定して変更します" : "Change the color of the role by specifying it in RGB",
        "赤の値 (0-255)" : "Red value (0-255)",
        "緑の値 (0-255)" : "Green value (0-255)",
        "青の値 (0-255)" : "Blue value (0-255)",
        "ロールの色を16進数カラーコードで指定して変更します" : "Change the color of the role by specifying it in hexadecimal color code",
        "16進数カラーコード (例: #ff5733)" : "Hexadecimal color code (e.g. #ff5733)",
        "無効な16進数カラーコードです: " : "Invalid hexadecimal color code: ",
        "ロールを作成します" : "Create a role",
        "ロール名" : "Role name",
        "そのロールを付与する" : "Grant that role",
        "ロールをメンション可能にする" : "Make the role mentionable",
        "はい" : "Give",
        "いいえ" : "Do not give",
        "このロールはこの時点では誰にも付与していません。" : "This role is not granted to anyone at this point.",
        "このロールはメンションできます。" : "This role can be mentioned.",
        "このロールはメンションできません。" : "This role cannot be mentioned.",
        "次のロールは既に存在します: " : "The following role already exists: ",
        "ロールを作成しました" : "Created a role",
        "作成されたロール: " : "Created role: ",
        "次のユーザーに付与しました: " : "Granted to the following user: ",
        "このbotがいくつのサーバーに入っているか確認できる" : "You can check how many servers this bot is in",
        "つのサーバーで稼働中" : " servers are running this bot",
        "ロールを作ります" : "Create a role",
    }
}