dictionary = {
    "en": {
        "ロールの色を変更しました": "Changed the color of the role",
        "変更されたロール：" : "Changed role: ",
        "エラー": "Error",
        "このbotに次のロールの色を変更する権限がありません: " : "This bot does not have permission to change the color of the following roles: ",
        "このbotのロールを一番上に設定するなどして、権限の調整を行ってから、再度試してみてください。" : "Please adjust the permissions by setting the role of this bot to the top and try again.",
        "次のロールが存在しません: " : "The following role does not exist: ",
        "色選択をする直前に削除されたものと思われます。" : "It seems that it was deleted just before selecting the color.",
        "ロールの色を変更します" : "Change the color of the role",
        "色を変更するロールを選択してください" : "Please select the role to change the color",
        "色を変更するロールの名前" : "Name of the role to change the color",
        "以下から色を選択してください" : "Please select a color from below",
        "色選択をキャンセルしました。" : "Color selection has been canceled.",
        "ロールの色をRGBで指定して変更します" : "Change the color of the role by specifying it in RGB",
        "赤の値 (0-255)" : "Red value (0-255)",
        "緑の値 (0-255)" : "Green value (0-255)",
        "青の値 (0-255)" : "Blue value (0-255)",
        "ロールの色を16進数カラーコードで指定して変更します" : "Change the color of the role by specifying it in hexadecimal color code",
        "16進数カラーコード (例: #ff5733)" : "Hexadecimal color code (e.g. #ff5733)",
        "無効な16進数カラーコードです: " : "Invalid hexadecimal color code: ",
        "ロールが存在しません。" : "The role does not exist.",
        "ロールを作成します" : "Create a role",
        "ロール名" : "Role name",
        "そのロールを付与する" : "Grant that role",
        "ロールをメンション可能にする" : "Make the role mentionable",
        "指定したロールを指定したメンバーに付与します" : "Grant the specified role to the specified member",
        "付与するロール" : "Role to grant",
        "付与するメンバー (省略するとあなた自身)" : "Member to grant (if omitted, yourself)",
        "サーバー内でのみ使用できるコマンドです。" : "This command can only be used within a server.",
        "このロールは外部サービスによって管理されているため付与できません。" : "This role cannot be granted because it is managed by an external service.",
        "情報" : "Information",
        "このメンバーは既にそのロールを持っています。" : "This member already has that role.",
        "このbotはそのロールを付与する権限がありません。サーバー内のロールの順位を確認してください。" : "This bot does not have permission to grant that role. Please check the role hierarchy in the server.",
        "ロールを付与しました" : "Granted the role",
        "付与されたロール: " : "Granted role: ",
        "ロール付与中にエラーが発生しました: " : "An error occurred while granting the role: ",
        "指定したメンバーから指定したロールを除去します" : "Remove the specified role from the specified member",
        "除去するロール" : "Role to remove",
        "対象メンバー (省略するとあなた自身)" : "Target member (if omitted, yourself)",
        "このロールは外部サービスによって管理されているため除去できません。" : "This role cannot be removed because it is managed by an external service.",
        "このメンバーはそのロールを持っていません。" : "This member does not have that role.",
        "ロールを除去しました" : "Removed the role",
        "除去されたロール: " : "Removed role: ",
        "対象ユーザー: " : "Target user: ",
        "このbotはそのロールを除去する権限がありません。サーバー内のロールの順位を確認してください。" : "This bot does not have permission to remove that role. Please check the role hierarchy in the server.",
        "ロール除去中にエラーが発生しました: " : "An error occurred while removing the role: ",
        "はい" : "Give",
        "いいえ" : "Do not give",
        "このロールはこの時点では誰にも付与していません。" : "This role is not granted to anyone at this point.",
        "このロールはメンションできます。" : "This role can be mentioned.",
        "このロールはメンションできません。" : "This role cannot be mentioned.",
        "次のロールは既に存在します: " : "The following role already exists: ",
        "ロールを作成しました" : "Created a role",
        "作成されたロール: " : "Created role: ",
        "次のユーザーに付与しました: " : "Granted to the following user: ",
        "ロールの付与に失敗しました。" : "Failed to grant role.",
        "削除" : "Delete",
        "キャンセル" : "Cancel",
        "この操作は実行者のみ行えます。" : "This operation can only be performed by the executor.",
        "ロールを削除しました" : "Deleted the role",
        "削除されたロール: " : "Deleted role: ",
        "このbotにそのロールを削除する権限がありません。サーバー内のロールの順位を確認してください。" : "This bot does not have permission to delete that role. Please check the role hierarchy in the server.",
        "ロール削除中にエラーが発生しました: " : "An error occurred while deleting the role: ",
        "ロールの削除をキャンセルしました。" : "Role deletion has been canceled.",
        "指定したロールをサーバーから削除します" : "Delete the specified role from the server",
        "削除するロールを選択してください" : "Please select the role to delete",
        "サーバー内でのみ使用できるコマンドです。" : "This command can only be used within a server.",
        "ロールが見つかりません。" : "Role not found.",
        "@everyone ロールは削除できません。" : "The @everyone role cannot be deleted.",
        "このロールは外部サービスによって管理されているため削除できません。" : "This role cannot be deleted because it is managed by an external service.",
        "このbotはそのロールを削除する権限がありません。サーバー内のロールの順位を確認してください。" : "This bot does not have permission to delete that role. Please check the role hierarchy in the server.",
        "このbotにロールを管理する権限(manage_roles)がありません。botの権限を確認してください。" : "This bot does not have permission to manage roles (manage_roles). Please check the bot's permissions.",
        "ロールを削除します" : "Delete a role",
        "本当に次のロールをサーバーから削除してもよろしいですか？\n削除されたロールは元に戻せません。\n" : "Are you sure you want to delete the following role from the server?\nDeleted roles cannot be restored.\n",
        "つのサーバーで稼働中" : " servers are running this bot",
        "ロールを作ります" : "Create a role",
    }
}